### PR TITLE
cameraview.cc: set alignment to 1 when copying texture

### LINKED ISSUE #24407: Webcam & Replay video is corrupted in the UI
### Describe the bug

Use case 1:
* Setup OP tools on Ubuntu 20.04, latest master, stock
* Run selfdrive/debug/uiview.py
* Observe corrupted video feed
image

Use case 2:
* Setup OP tools on Ubuntu 20.04, latest master, stock
* Compile for Webcam
* Observe corrupted video feed
image

### OS Version

Ubuntu 20.04

### openpilot version or commit

05f606c8121c89990225ff873c2779fcb3790ead

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by pd0wm**
Needed for webcam/C2. Seems to work fine on C3 without this change.

### CODE REVIEW

File: selfdrive/ui/qt/widgets/cameraview.cc [hunk 1]
```diff
@@ -238,6 +239,7 @@ void CameraViewWidget::paintGL() {
   glBindVertexArray(0);
   glBindTexture(GL_TEXTURE_2D, 0);
   glActiveTexture(GL_TEXTURE0);
+  glPixelStorei(GL_UNPACK_ALIGNMENT, 4);
```
Comment (pd0wm) [inline selfdrive/ui/qt/widgets/cameraview.cc:242]: Make sure to put back to 4 to not break font rendering.
