### PR TITLE
swaglog: delay creating zmq socket to first use - fix modeld crash in sim

### LINKED ISSUE #23666: CARLA: modeld crashes on startup
### Describe the bug

As CARLA is open and I try to start the cruise by pressing key 1, an error message appears. openpilot Unavailable Interprocess communication problem 

How to reproduce the error.
Open a terminal and run the command
cd tools/sim ./start_carla.sh

Open another terminal and run the command
cd tools/sim ./start_openpilot_docker.sh

Press 1 a few times while focused on bridge.py 

image
image

### OS Version

Ubuntu 20.04

### openpilot version or commit

a5844363280ec4bafba9eaf046813f16aba6d6ac

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by gijskoning**
Fixes modeld crash in simulator. The zmq_socket was created at import leading to two sockets in one thread. This pr calls initialize() on the first usage of the logs.
Problem started here: https://github.com/commaai/openpilot/pull/23596

Fixes https://github.com/commaai/openpilot/issues/23666
And prs https://github.com/commaai/openpilot/pull/24203 and https://github.com/commaai/openpilot/pull/23792 can be closed.

### CODE REVIEW

File: selfdrive/common/statlog.cc [hunk 1]
```diff
@@ -17,6 +17,8 @@ class StatlogState : public LogState {
 static StatlogState s = {};
 
 static void log(const char* metric_type, const char* metric, const char* fmt, ...) {
+  if (!s.initialized) s.initialize();
```
Comment (pd0wm) [inline selfdrive/common/statlog.cc:20]: You want to take the lock like in `cloudlog_common`, this can cause race conditions if multiple threads call `log` at the same time.

File: selfdrive/common/util.h [hunk 2]
```diff
@@ -182,7 +188,9 @@ class LogState {
     zmq_setsockopt(sock, ZMQ_LINGER, &timeout, sizeof(timeout));
 
     zmq_connect(sock, endpoint);
-  };
+    initialized = true;
+  }
+
   ~LogState() {
     zmq_close(sock);
```
Comment (pd0wm) [inline selfdrive/common/util.h:195]: You can reach this code now with an uninialized `LogState`. Check for `initialized` or you'll try to close an unopened socket.

Also set `zctx` and `sock` to `nullptr` as default values just to be sure.
