### PR TITLE
replay: increase file descriptor limit macOS

### LINKED ISSUE #29281: [macOS] unable to run replay: Assertion failed: (*fd >= 0), function malloc_with_fd, file visionbuf_cl.cc, line 24.
### Describe the bug

environment:
* macbook m1
* ventura 13.4.1

the command below caused the issue:
```python
./replay --data_dir /Users/ricklan/projects/realdata "0000000000000000|2023-08-05--20-19-31"
```

however, if I add --no-vipc then I can replay the route without video stream just fine:
```python
./replay --data_dir /Users/ricklan/projects/realdata "0000000000000000|2023-08-05--20-19-31" --no-vipc
```

Screenshot 2023-08-08 at 11 26 00 PM

### OS Version

macOS ventura 13.4.1

### openpilot version or commit

95289cb180ac53cbe0f522fcbd81a8ad0019a2cc

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by fredyshox**
Each ZMQ socket takes 3 descriptors on macOS (2 on linux). 71 services = 213 descriptors. VIPC creates 40 buffers = 40 descriptors. Add some networking and open some files, and we easily hit 256 limit.

Seems like for a while replay was right on the edge of the fd limit on macOS.

Fixes: #29281

### CODE REVIEW

File: tools/replay/main.cc [hunk 1]
```diff
@@ -4,8 +4,14 @@
 #include "common/prefix.h"
 #include "tools/replay/consoleui.h"
 #include "tools/replay/replay.h"
+#include "tools/replay/util.h"
 
 int main(int argc, char *argv[]) {
+#ifdef __APPLE__
+  // With all sockets opened, we might hit the default limit of 256 on macOS
+  setFileDescriptorLimit(1024);
```
Comment (adeebshihadeh) [inline tools/replay/main.cc:12]: this doesn't have anything to do with replay, should probably go in the messaging backend

**Review by adeebshihadeh — CHANGES_REQUESTED** [review]

File: tools/replay/main.cc (hunk 1 above)
Comment (fredyshox) [reply tools/replay/main.cc:12]: But it only affects replay process, because of extensive of sockets. Not every process needs to increase that limit, since most processes use only a couple of sockets at most. So I'd argue that it's the process responsibility to handle that.

Comment (fredyshox) [reply tools/replay/main.cc:12]: But it could be moved elsewhere, so each process would be able to set it up if needed. Maybe `common/util.cc`?

Comment (fredyshox) [reply tools/replay/main.cc]: Moved `set_file_descriptor_limit` to common, so its accessible to other tools/processes if ever needed.
