### PR TITLE
ui: prevent constant clicking on experimental button

### LINKED ISSUE #27703: ui: ignore steering icon double taps
### Describe the bug

When tapping the steering icon in the upper right corner to switch between chill and experimental modes, a second tap is sometimes registered causing the mode to change twice rapidly which results in the mode basically staying the same.

This is most likely to happen while driving while the device and user are in motion. A small button tap delay such as 0.5s may help with this.

### Provide a route where the issue occurs

1a5d045d2c531a6d

### openpilot version

master

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/27703

### CODE REVIEW

File: selfdrive/ui/qt/onroad.cc [hunk 1]
```diff
@@ -180,12 +180,13 @@ ExperimentalButton::ExperimentalButton(QWidget *parent) : QPushButton(parent) {
...
-  params = Params();
   engage_img = loadPixmap("../assets/img_chffr_wheel.png", {img_size, img_size});
   experimental_img = loadPixmap("../assets/img_experimental.svg", {img_size, img_size});
 
-  QObject::connect(this, &QPushButton::toggled, [=](bool checked) {
-    params.putBool("ExperimentalMode", checked);
+  QObject::connect(this, &QPushButton::toggled, [this](bool checked) {
+    setEnabled(false);
+    Params().putBool("ExperimentalMode", checked);
+    QTimer::singleShot(1000, [this]() { setEnabled(true); });
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:189]: How about 100ms? I feel like the double clicks are tens of ms apart, not on the order of hundres

Comment (sshane) [reply selfdrive/ui/qt/onroad.cc:189]: yep, a second button press is registered about 20 ms after, I've reproduced this a few times now.

Comment (deanlee) [reply selfdrive/ui/qt/onroad.cc]: > Though, it would be even better to debounce all UI buttons generically, can we do that?
y, think we can do it in another pr.

Comment (sshane) [reply selfdrive/ui/qt/onroad.cc]: there's a race condition with the onroad ExperimentalButton. the button signal `toggled` causes a param write, which controlsd reads and sends in `controlsState`, which `ExperimentalButton` reads to set checked...which writes the param again. So if you get a toggled signal, and then an old controlsState packet it will write twice!

you can  also write the param through another mean and ExperimentalButton will write it again (the `setChecked` call sends a `toggled` signal)

Comment (deanlee) [reply selfdrive/ui/qt/onroad.cc]: Where is the parameter ExperimentalModeConfirmed set?

Comment (sshane) [reply selfdrive/ui/qt/onroad.cc]: controls.h `bool confirmed = store_confirm && params.getBool(key + "Confirmed");`

**Comment by deanlee** [comment]
still use 1000ms to prevent check ExperimentalMode in updatestate before timeout,  @sshane Is  one second timeout enough for this? should we increase the timeout to make sure the mode is switched before timeout?

File: selfdrive/ui/qt/onroad.cc [hunk 2]
```diff
@@ -180,12 +180,14 @@ ExperimentalButton::ExperimentalButton(QWidget *parent) : QPushButton(parent) {
...
   engage_img = loadPixmap("../assets/img_chffr_wheel.png", {img_size, img_size});
   experimental_img = loadPixmap("../assets/img_experimental.svg", {img_size, img_size});
 
-  QObject::connect(this, &QPushButton::toggled, [=](bool checked) {
-    params.putBool("ExperimentalMode", checked);
+  QObject::connect(this, &QPushButton::clicked, [this](bool checked) {
+    setEnabled(false);
+    Params().putBool("ExperimentalMode", checked);
+    // prevent double click and skip check for experimental mode in updateState before timeout.
+    QTimer::singleShot(1000, [this]() { setEnabled(true); });
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:190]:
```suggestion
    QTimer::singleShot(100, [this]() { setEnabled(true); });
```

yes 100ms sounds good. the fact that this rarely happens means that the param must be getting read in one control frame most of the time

File: selfdrive/ui/qt/onroad.cc [hunk 3]
```diff
@@ -180,12 +180,14 @@ ExperimentalButton::ExperimentalButton(QWidget *parent) : QPushButton(parent) {
   setFixedSize(btn_size, btn_size);
   setCheckable(true);
 
-  params = Params();
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:183]: why delete?

Comment (deanlee) [reply selfdrive/ui/qt/onroad.cc:183]: sorry my bad

File: selfdrive/ui/qt/onroad.cc [hunk 4]
```diff
@@ -197,7 +200,9 @@ void ExperimentalButton::updateState(const UIState &s) {
   setVisible(cs.getEngageable() || cs.getEnabled());
 
   // button is "checked" if experimental mode is enabled
-  setChecked(sm["controlsState"].getControlsState().getExperimentalMode());
+  if (isEnabled()) {
+    setChecked(sm["controlsState"].getControlsState().getExperimentalMode());
+  }
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:205]: What if we always update from controlsState and disallow clicking to change the checked state? Then we make no assumptions about how long the round trip from setting param to controlsd reading it, to it sending it out with cereal?

Comment (deanlee) [reply selfdrive/ui/qt/onroad.cc:205]: In my opinion, this experimental button may not belong here at all. All other icons in the HUD cannot be clicked, only this one can, and there is no visual difference. This is a very strange thing, and users who are not familiar with it would not understand its purpose. Perhaps such a button should only exist in the settings interface.

**Comment by deanlee** [comment]
The new commit made the following changes:
1. removed the checkable state of the button, use a member variable `experimental_mode` to save the current mode, this greatly simplifies the logic for handling clicks.
2. read params in changeMode to determine whether it is possible to switch modes, instead of doing two slow I/O operations every time 'updateState' is called.
3. the timer is no longer used to prevent users from repeatedly clicking because even if the user clicks repeatedly, the value write to param 'ExperimentalMode' will not change.

File: selfdrive/ui/qt/onroad.cc [hunk 5]
```diff
@@ -174,43 +174,41 @@ void OnroadAlerts::paintEvent(QPaintEvent *event) {
...
-    params.putBool("ExperimentalMode", checked);
-  });
+void ExperimentalButton::changeMode() {
+  auto params = Params();
+  const auto cp = (*uiState()->sm)["carParams"].getCarParams();
+  const bool experimental_mode_available = cp.getExperimentalLongitudinalAvailable() ? params.getBool("ExperimentalLongitudinalEnabled") : cp.getOpenpilotLongitudinalControl();
+  bool can_change = experimental_mode_available && params.getBool("ExperimentalModeConfirmed");
+  if (can_change) {
+    params.putBool("ExperimentalMode", !experimental_mode);
+  }
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:194]: Can we make a global variable or helper function to consolidate all of this experimental/alpha longitudinal logic? I think we have very similar logic in settings.cc as well as here which is pretty confusing to keep track of

Comment (deanlee) [reply selfdrive/ui/qt/onroad.cc:194]: How about implementing it in another PR? 
Think it would be better to make a more comprehensive implementation instead of just targeting this specific functionality.For example, adding a member variable "struct settings" to `uistate` to track all changes in settings. This way, most calls to the `param.read` in the UI can be eliminated. It also allows for real-time switching of states, such as between miles and kilometers.

File: selfdrive/ui/qt/onroad.cc [hunk 6]
```diff
@@ -174,43 +174,41 @@ void OnroadAlerts::paintEvent(QPaintEvent *event) {
...
   engage_img = loadPixmap("../assets/img_chffr_wheel.png", {img_size, img_size});
   experimental_img = loadPixmap("../assets/img_experimental.svg", {img_size, img_size});
+  QObject::connect(this, &QPushButton::clicked, this, &ExperimentalButton::changeMode);
+}
 
-  QObject::connect(this, &QPushButton::toggled, [=](bool checked) {
-    params.putBool("ExperimentalMode", checked);
-  });
+void ExperimentalButton::changeMode() {
+  auto params = Params();
```
Comment (sshane) [inline selfdrive/ui/qt/onroad.cc:188]: any reason to create params every time?

**Comment by sshane** [comment]
looks mostly good to me, @incognitojam can you check it out and merge? Only thing is the duplicate logic, but that's not new with this PR and we can clean it up soon in another
