### PR TITLE
 ui: re-generate JWT on valid system time

### LINKED ISSUE #32398: ui: map doesn't load if time is wrong at the start
The JWT used to auth with the map tile server is only created once on map init, but it relies on the time being correct (which is no longer guaranteed at the time of map init). We need to generate a new JWT on every request or failed request to fix this. 

Similar fix for navd: https://github.com/commaai/openpilot/commit/76c5c58d540db580d7b09c2489a6e3ff7ae3c2cc

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

File: selfdrive/ui/qt/maps/map.cc [hunk 1]
```diff
@@ -253,6 +254,15 @@ void MapWindow::initializeGL() {
   m_map->setPitch(MIN_PITCH);
   m_map->setStyleUrl("mapbox://styles/commaai/clkqztk0f00ou01qyhsa5bzpj");
 
+  QObject::connect(m_map.data(), &QMapLibre::Map::mapLoadingFailed, [=](QMapLibre::Map::MapLoadingFailure err_code, const QString &reason) {
+    LOGE("Map loading failed with %d: '%s'\n", err_code, reason.toStdString().c_str());
+    // if time is wrong, re-create token and try connecting again in 5s
+    if (err_code == QMapLibre::Map::MapLoadingFailure::StyleLoadFailure && reason.contains("SSL handshake failed")) {
```
Comment (adeebshihadeh) [inline selfdrive/ui/qt/maps/map.cc:260]: checking an error string is generally fragile. style load failure might also just happen to be the first thing that MapLibre loads now, and it could easily change in the future

Comment (sshane) [reply selfdrive/ui/qt/maps/map.cc:260]: This comes from mbgl: https://github.com/maplibre/maplibre-native-qt/blob/3a83b8ecfd961983cf3670a145ef6176333dd443/src/core/map_observer.cpp#L59-L60

Which is this section: https://github.com/mapbox/mapbox-gl-native/blob/f2778251c97ba3403582b9c04290c50f927fd338/src/mbgl/map/map_impl.cpp#L98-L100

So this is the source: https://github.com/mapbox/mapbox-gl-native/blob/f2778251c97ba3403582b9c04290c50f927fd338/src/mbgl/style/style_impl.cpp#L71-L75

So checking for the error code should be safe as we only load the style once, but we can remove the reason check which will just open us up to retrying for 404/403, etc.

**Comment by adeebshihadeh** [comment]
We can also wait for the time, like this https://github.com/commaai/openpilot/blob/5f778c0d3a740b271d10b10842406a97bd27d959/common/time.py#L14.

Up to you if you think that's simpler or not.

**Comment by sshane** [comment]
:thinking: 

image

**Comment by sshane** [comment]
Played around with making the time go in/valid with timed running, works as expected. Here I launched it with a date in 2023.

https://github.com/commaai/openpilot/assets/25857203/4bc3dc7d-3188-4693-859e-0a4cb42b7f05

File: common/util.cc [hunk 2]
```diff
@@ -271,4 +275,20 @@ std::string check_output(const std::string& command) {
...
+  std::filesystem::path systemd_path("/lib/systemd/systemd");
+  if (std::filesystem::exists(systemd_path)) {
+    auto ftime = std::filesystem::last_write_time(systemd_path);
+    auto stime = std::chrono::time_point_cast<std::chrono::system_clock::duration>(ftime - std::filesystem::file_time_type::clock::now() + std::chrono::system_clock::now());
+    return stime + std::chrono::hours(24);
+  }
+  return _MIN_DATE;
+}
+
+bool system_time_valid() {
```
[the remark this answers is not in the document]
Comment (sshane) [reply common/util.cc]: I didn't merge this in
