### PR TITLE
soundd

### LINKED ISSUE #21573: Break out sounds into soundd
soundd's responsibilities:
* play alert sounds
* detect when we can't play sounds (pulseaudio crash, etc.)
* detect when we can't show the UI (UI/surfaceflinger crash, etc.)

### PR DESCRIPTION
**Pull request by adeebshihadeh**

### CODE REVIEW

**Comment by pd0wm** [comment]
Any meaningful CPU usage? See you didn't add it to the onroad tests yet.

File: selfdrive/ui/soundd.cc [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+
+private:
+  Alert alert;
+  float volume = Hardware::MIN_VOLUME;
+  std::map<AudibleAlert, std::pair<QSoundEffect, int>> sounds;
+  SubMaster *sm;
+};
+
+int main(int argc, char **argv) {
+  // TODO: priority? can't mismatch UI too much
```
Comment (pd0wm) [inline selfdrive/ui/soundd.cc:96]: Maybe give ui and soundd some niceness (like loggerd)?

**Comment by adeebshihadeh** [comment]
CPU usage is 2% at idle, but goes up significantly while play sounds.
