### PR TITLE
camerad: fix tearing when hitting frame timeout

### LINKED ISSUE #34429: Forward video has tearing artifacts Jan 2025
### Describe the bug

Admittedly, I am running a week old+ build of openpilot master-ci. I haven't been driving much so it's been a bit stale/outdated.

This issue was previously seen in https://github.com/commaai/openpilot/issues/33998 and was thought be resolved. It might have even been resolved after the week+ old build of master-ci . This is on a build that's come after and post-fix?

https://connect.comma.ai/fe18f736cb0d7813/000004f2--18b34fab74

At the moment, I haven't uploaded everything yet as I'm not on a great internet connection. Will do once I am.

Clipper:
https://connect.comma.ai/fe18f736cb0d7813/000004f2--18b34fab74/77/181

UI:

https://github.com/user-attachments/assets/cce071ab-2cbe-4d18-b316-e54ba2ffadd9

Forward:

https://github.com/user-attachments/assets/e5c7d334-450f-4db9-9109-f35b33ab5f65

Wide:

https://github.com/user-attachments/assets/3c567219-ddf6-4d23-a3c7-e2fe08dd425a

Driver:
Looks fine to me.

---

Anyway, just documenting this here in-case this hasn't been fixed after #33998 .

### Provide a route where the issue occurs

fe18f736cb0d7813/000004f2--18b34fab74

### openpilot version

master-ci

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by sshane**
Closes https://github.com/commaai/openpilot/issues/34429

Small random timeout w/ ISP debayer enabled on ecam and dcam:

master:

https://github.com/user-attachments/assets/072b32b7-c0a8-4d92-b59e-efa571748080

This PR:

https://github.com/user-attachments/assets/0862f45f-cb17-4f4b-bfdc-672b4870dbe6

### CODE REVIEW

File: system/camerad/cameras/spectra.cc [hunk 1]
```diff
@@ -683,13 +683,12 @@ void SpectraCamera::enqueue_buffer(int i, bool dp) {
...
     if (ret != 0) {
-      // TODO: handle frame drop cleanly
-      // when this happens, it messes up future frames
+      clear_req_queue();
       LOGE("failed to wait for sync: %d %d", ret, sync_wait.sync_obj);
     }
     buf.frame_metadata[i].timestamp_end_of_isp = (uint64_t)nanos_since_boot();
     buf.frame_metadata[i].timestamp_eof = buf.frame_metadata[i].timestamp_sof + sensor->readout_time_ns;
-    if (dp) {
+    if (dp && ret == 0) {
```
Comment (sshane) [inline system/camerad/cameras/spectra.cc:691]: with a low timeout (`rand() % 30 + 10`), without this, you would still sometimes see occasional tearing due to using the incomplete frame, even if we cleared the request queue

**Review by adeebshihadeh — APPROVED** [review]

**Comment by adeebshihadeh** [comment]
Let's re-enable ISP once this is merged.

**Comment by sshane** [comment]
This is what it looks when waiting on the frame times out one singular time (yes, there's also a two frame diff of frameId and frameIdSensor without ISP debayer), everything recovers in ~10 frames:

image
